FROM inshopgroup/docker-inshop-crm-api-php-fpm-prod:latest

WORKDIR /var/www
ADD ./ /var/www

RUN composer install --optimize-autoloader
RUN chown -R www-data:www-data /var/www

CMD /var/www/bin/entrypoint.sh
